# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dht_pb2 as dht__pb2


class DHTServiceStub(object):
    """DHT Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/dht.DHTService/Put',
                request_serializer=dht__pb2.PutRequest.SerializeToString,
                response_deserializer=dht__pb2.PutResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/dht.DHTService/Get',
                request_serializer=dht__pb2.GetRequest.SerializeToString,
                response_deserializer=dht__pb2.GetResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/dht.DHTService/HealthCheck',
                request_serializer=dht__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=dht__pb2.HealthCheckResponse.FromString,
                )
        self.InternalPut = channel.unary_unary(
                '/dht.DHTService/InternalPut',
                request_serializer=dht__pb2.InternalPutRequest.SerializeToString,
                response_deserializer=dht__pb2.InternalPutResponse.FromString,
                )
        self.InternalGet = channel.unary_unary(
                '/dht.DHTService/InternalGet',
                request_serializer=dht__pb2.InternalGetRequest.SerializeToString,
                response_deserializer=dht__pb2.InternalGetResponse.FromString,
                )
        self.ReadRepair = channel.unary_unary(
                '/dht.DHTService/ReadRepair',
                request_serializer=dht__pb2.ReadRepairRequest.SerializeToString,
                response_deserializer=dht__pb2.ReadRepairResponse.FromString,
                )


class DHTServiceServicer(object):
    """DHT Service Definition
    """

    def Put(self, request, context):
        """Client-facing operations
        Put operation to store a key-value pair
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get operation to retrieve a value by key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for node availability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalPut(self, request, context):
        """Internal operations (node-to-node)
        Internal put for replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalGet(self, request, context):
        """Internal get for quorum reads
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRepair(self, request, context):
        """Read repair operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DHTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=dht__pb2.PutRequest.FromString,
                    response_serializer=dht__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=dht__pb2.GetRequest.FromString,
                    response_serializer=dht__pb2.GetResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=dht__pb2.HealthCheckRequest.FromString,
                    response_serializer=dht__pb2.HealthCheckResponse.SerializeToString,
            ),
            'InternalPut': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalPut,
                    request_deserializer=dht__pb2.InternalPutRequest.FromString,
                    response_serializer=dht__pb2.InternalPutResponse.SerializeToString,
            ),
            'InternalGet': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalGet,
                    request_deserializer=dht__pb2.InternalGetRequest.FromString,
                    response_serializer=dht__pb2.InternalGetResponse.SerializeToString,
            ),
            'ReadRepair': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRepair,
                    request_deserializer=dht__pb2.ReadRepairRequest.FromString,
                    response_serializer=dht__pb2.ReadRepairResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dht.DHTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DHTService(object):
    """DHT Service Definition
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dht.DHTService/Put',
            dht__pb2.PutRequest.SerializeToString,
            dht__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dht.DHTService/Get',
            dht__pb2.GetRequest.SerializeToString,
            dht__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dht.DHTService/HealthCheck',
            dht__pb2.HealthCheckRequest.SerializeToString,
            dht__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InternalPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dht.DHTService/InternalPut',
            dht__pb2.InternalPutRequest.SerializeToString,
            dht__pb2.InternalPutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InternalGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dht.DHTService/InternalGet',
            dht__pb2.InternalGetRequest.SerializeToString,
            dht__pb2.InternalGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRepair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dht.DHTService/ReadRepair',
            dht__pb2.ReadRepairRequest.SerializeToString,
            dht__pb2.ReadRepairResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
