# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dht_pb2 as dht__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dht_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DHTServiceStub(object):
    """DHT Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/dht.DHTService/Put',
                request_serializer=dht__pb2.PutRequest.SerializeToString,
                response_deserializer=dht__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/dht.DHTService/Get',
                request_serializer=dht__pb2.GetRequest.SerializeToString,
                response_deserializer=dht__pb2.GetResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/dht.DHTService/HealthCheck',
                request_serializer=dht__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=dht__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.InternalPut = channel.unary_unary(
                '/dht.DHTService/InternalPut',
                request_serializer=dht__pb2.InternalPutRequest.SerializeToString,
                response_deserializer=dht__pb2.InternalPutResponse.FromString,
                _registered_method=True)
        self.InternalGet = channel.unary_unary(
                '/dht.DHTService/InternalGet',
                request_serializer=dht__pb2.InternalGetRequest.SerializeToString,
                response_deserializer=dht__pb2.InternalGetResponse.FromString,
                _registered_method=True)
        self.ReadRepair = channel.unary_unary(
                '/dht.DHTService/ReadRepair',
                request_serializer=dht__pb2.ReadRepairRequest.SerializeToString,
                response_deserializer=dht__pb2.ReadRepairResponse.FromString,
                _registered_method=True)
        self.GetRing = channel.unary_unary(
                '/dht.DHTService/GetRing',
                request_serializer=dht__pb2.GetRingRequest.SerializeToString,
                response_deserializer=dht__pb2.GetRingResponse.FromString,
                _registered_method=True)
        self.JoinCluster = channel.unary_unary(
                '/dht.DHTService/JoinCluster',
                request_serializer=dht__pb2.JoinClusterRequest.SerializeToString,
                response_deserializer=dht__pb2.JoinClusterResponse.FromString,
                _registered_method=True)
        self.InternalPutWithHint = channel.unary_unary(
                '/dht.DHTService/InternalPutWithHint',
                request_serializer=dht__pb2.InternalPutWithHintRequest.SerializeToString,
                response_deserializer=dht__pb2.InternalPutWithHintResponse.FromString,
                _registered_method=True)
        self.DeliverHint = channel.unary_unary(
                '/dht.DHTService/DeliverHint',
                request_serializer=dht__pb2.DeliverHintRequest.SerializeToString,
                response_deserializer=dht__pb2.DeliverHintResponse.FromString,
                _registered_method=True)
        self.InspectNode = channel.unary_unary(
                '/dht.DHTService/InspectNode',
                request_serializer=dht__pb2.InspectNodeRequest.SerializeToString,
                response_deserializer=dht__pb2.InspectNodeResponse.FromString,
                _registered_method=True)


class DHTServiceServicer(object):
    """DHT Service Definition
    """

    def Put(self, request, context):
        """Client-facing operations
        Put operation to store a key-value pair
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get operation to retrieve a value by key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for node availability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalPut(self, request, context):
        """Internal operations (node-to-node)
        Internal put for replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalGet(self, request, context):
        """Internal get for quorum reads
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRepair(self, request, context):
        """Read repair operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRing(self, request, context):
        """Get ring information (for node discovery)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinCluster(self, request, context):
        """Join cluster (notify other nodes of our presence)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalPutWithHint(self, request, context):
        """Hinted Handoff operations
        Internal put with hint (for sloppy quorum)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverHint(self, request, context):
        """Deliver hint to target node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DHTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=dht__pb2.PutRequest.FromString,
                    response_serializer=dht__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=dht__pb2.GetRequest.FromString,
                    response_serializer=dht__pb2.GetResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=dht__pb2.HealthCheckRequest.FromString,
                    response_serializer=dht__pb2.HealthCheckResponse.SerializeToString,
            ),
            'InternalPut': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalPut,
                    request_deserializer=dht__pb2.InternalPutRequest.FromString,
                    response_serializer=dht__pb2.InternalPutResponse.SerializeToString,
            ),
            'InternalGet': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalGet,
                    request_deserializer=dht__pb2.InternalGetRequest.FromString,
                    response_serializer=dht__pb2.InternalGetResponse.SerializeToString,
            ),
            'ReadRepair': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRepair,
                    request_deserializer=dht__pb2.ReadRepairRequest.FromString,
                    response_serializer=dht__pb2.ReadRepairResponse.SerializeToString,
            ),
            'GetRing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRing,
                    request_deserializer=dht__pb2.GetRingRequest.FromString,
                    response_serializer=dht__pb2.GetRingResponse.SerializeToString,
            ),
            'JoinCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinCluster,
                    request_deserializer=dht__pb2.JoinClusterRequest.FromString,
                    response_serializer=dht__pb2.JoinClusterResponse.SerializeToString,
            ),
            'InternalPutWithHint': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalPutWithHint,
                    request_deserializer=dht__pb2.InternalPutWithHintRequest.FromString,
                    response_serializer=dht__pb2.InternalPutWithHintResponse.SerializeToString,
            ),
            'DeliverHint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverHint,
                    request_deserializer=dht__pb2.DeliverHintRequest.FromString,
                    response_serializer=dht__pb2.DeliverHintResponse.SerializeToString,
            ),
            'InspectNode': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectNode,
                    request_deserializer=dht__pb2.InspectNodeRequest.FromString,
                    response_serializer=dht__pb2.InspectNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dht.DHTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dht.DHTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DHTService(object):
    """DHT Service Definition
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/Put',
            dht__pb2.PutRequest.SerializeToString,
            dht__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/Get',
            dht__pb2.GetRequest.SerializeToString,
            dht__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/HealthCheck',
            dht__pb2.HealthCheckRequest.SerializeToString,
            dht__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InternalPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/InternalPut',
            dht__pb2.InternalPutRequest.SerializeToString,
            dht__pb2.InternalPutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InternalGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/InternalGet',
            dht__pb2.InternalGetRequest.SerializeToString,
            dht__pb2.InternalGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRepair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/ReadRepair',
            dht__pb2.ReadRepairRequest.SerializeToString,
            dht__pb2.ReadRepairResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/GetRing',
            dht__pb2.GetRingRequest.SerializeToString,
            dht__pb2.GetRingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/JoinCluster',
            dht__pb2.JoinClusterRequest.SerializeToString,
            dht__pb2.JoinClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InternalPutWithHint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/InternalPutWithHint',
            dht__pb2.InternalPutWithHintRequest.SerializeToString,
            dht__pb2.InternalPutWithHintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverHint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/DeliverHint',
            dht__pb2.DeliverHintRequest.SerializeToString,
            dht__pb2.DeliverHintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dht.DHTService/InspectNode',
            dht__pb2.InspectNodeRequest.SerializeToString,
            dht__pb2.InspectNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
